schedule: "0 * * * *"

startingDeadlineSeconds: {}

job:
  retries: 1
  timeout: 1800

annotations: {}

image:
  tag: latest

newRelic:
  image:
    repository: {}
    tag: {}
    appName: {}
    licenseKey: {}
  


env: {}
# example
# env:
#   RAILS_ENV: staging

envSecrets: {}
# example
# envSecrets:
#   MONGODB_USER: mongodb

envFrom: {}
# example
# envFrom:
#   configMapRef:
#     - test-1-env
#     - test-2-env
#   secretRef:
#     - test-1-secret
#     - test-2-secret

serviceaccount: {}
# example
# serviceaccount:
#   annotations:
#     eks.amazonaws.com/role-arn: <aws-role-arn>
#     name: <serviceaccount-name>
