{{- if and (.Values.kind ) (eq .Values.kind "CronWorkflow") }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
{{- else }}
apiVersion: batch/v1beta1
kind: CronJob
{{- end }}
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- if and (.Values.kind ) (eq .Values.kind "CronWorkflow") }}
  timezone: {{ .Values.timezone | default "Asia/Taipei" }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.job.history.success | default 3 }}
  failedJobsHistoryLimit: {{ .Values.job.history.failed | default 1 }}
  concurrencyPolicy: {{ .Values.job.concurrency | default "Allow" }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  {{- if and (.Values.kind ) (eq .Values.kind "CronWorkflow") }}
  {{ template "cronjob.argo_cron_workflow" . }}
  {{- else }}
  {{ template "cronjob.k8s_cronjob" . }}
  {{- end}}
  